// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzoX-vIVcFbT_zktUvM8k5xw9YT5OeBWA',
    appId: '1:300993421695:web:28da9d411b2f77f0fdba4a',
    messagingSenderId: '300993421695',
    projectId: 'safety-first-8973c',
    authDomain: 'safety-first-8973c.firebaseapp.com',
    databaseURL: 'https://safety-first-8973c-default-rtdb.firebaseio.com',
    storageBucket: 'safety-first-8973c.appspot.com',
    measurementId: 'G-ESKVB2P29G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0U2n9yO9ukKxhvDvYFCykGhzN4w1Uz8o',
    appId: '1:300993421695:android:c632bd91871cbb1bfdba4a',
    messagingSenderId: '300993421695',
    projectId: 'safety-first-8973c',
    databaseURL: 'https://safety-first-8973c-default-rtdb.firebaseio.com',
    storageBucket: 'safety-first-8973c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeepSbOvD2Ho5R01PcQas-_7KORnLMIxA',
    appId: '1:300993421695:ios:eaad2c9e089fdcaefdba4a',
    messagingSenderId: '300993421695',
    projectId: 'safety-first-8973c',
    databaseURL: 'https://safety-first-8973c-default-rtdb.firebaseio.com',
    storageBucket: 'safety-first-8973c.appspot.com',
    iosBundleId: 'com.example.safety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeepSbOvD2Ho5R01PcQas-_7KORnLMIxA',
    appId: '1:300993421695:ios:06438f8431359e0dfdba4a',
    messagingSenderId: '300993421695',
    projectId: 'safety-first-8973c',
    databaseURL: 'https://safety-first-8973c-default-rtdb.firebaseio.com',
    storageBucket: 'safety-first-8973c.appspot.com',
    iosBundleId: 'com.example.safety.RunnerTests',
  );
}
